permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://aydintd.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: aydintd
archive: Depo
assets: /assets
author: Aydın Doyak
disqus: aydintd
email: aydintd@bil.omu.edu.tr
googleanalyticsid: UA-37492706-1
facebook: https://facebook.com/aydindoyak
logo: /assets/19/19-normal-128x128.png
organization: 19
related: Diğer Girdiler
repository: aydintd.github.com
ribbon:
title: Aydın Doyak
twitter: http://twitter.com/aydintd_

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
